export const detalheCeleDire = {
    "adult": false,
    "also_known_as": [
        "The Rock",
        "Rocky Maivia",
        "Скеля",
        "Big Bull",
        "Flex Kavana",
        "Dwayne Douglas Johnson",
        "Ντουέιν Ντάγκλας Τζόνσον",
        "La Roca",
        "Dwayne ‘The Rock’ Johnson",
        "الصخرة",
        "The Great One",
        "Скала",
        "דווין ג'ונסון",
        "ロック様",
        "ザ・ロック",
        "Hollywood Rock",
        "The Final Boss",
        "더 락",
        "The Blue Chipper",
        "The No. 1 Man in the Business",
        "The Most Electrifying Man",
        "Brahma Bull",
        "The People's Champion",
        "دوین جانسون",
        "巨石強森",
        "Дуэйн Джонсон"
    ],
    "biography": "Dwayne Douglas Johnson (Hayward, 2 de maio de 1972), conhecido pelo nome artístico The Rock, é um ator, produtor e lutador américo-canadense. Johnson também foi um jogador de futebol americano universitário pela Universidade de Miami, vencendo o campeonato nacional em 1991 pelo Miami Hurricanes. Também atuou pelo Calgary Stampeders na Liga Canadense de Futebol, sendo cortado após dois meses durante a temporada de 1995. Mais tarde tornou-se lutador profissional como seu avô, Peter Maivia, e seu pai, Rocky Johnson (de quem ele também herdou sua cidadania canadense).",
    "birthday": "1972-05-02",
    "deathday": null,
    "gender": 2,
    "homepage": "https://wwe.com/superstars/the-rock",
    "id": 18918,
    "imdb_id": "nm0425005",
    "known_for_department": "Acting",
    "name": "Dwayne Johnson",
    "place_of_birth": "Hayward, California, USA",
    "popularity": 5.122,
    "profile_path": "/5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg"
}